defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Kevin Van Kessel"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: :categories/:year/:month/:day/:title

url: https://vankessel.io
description: "A blog about programming, math, and machine learning."
