defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "K van Kessel"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: :title

port: 8080

plugins:
  - jekyll-redirect-from

author: "K van Kessel"
title: "K van Kessel"
url: https://vankessel.io
domain: vankessel.io
description: "A blog about programming, math, and machine learning."

feed_items: 10
feed_update_period: weekly
feed_update_frequency: 1
