defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Kara van Kessel"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: :title

port: 8080

plugins:
  - jekyll-redirect-from

author: "Kara van Kessel"
title: "Kara van Kessel"
url: https://vankessel.io
domain: vankessel.io
description: "A blog for my thoughts. Mostly philosophy, math, and programming."

feed_items: 10
feed_update_period: weekly
feed_update_frequency: 1
